# This is a basic workflow to help you get started with Actions

name: GitHub Actions Build and Deploy Demo

# Controls when the action will run. Triggers the workflow on push request events 
# but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Install and Build
      run: |
        npm install
        npm run build

    - name: Custom domain
      run: echo 'www.ipyth.com' > CNAME
      working-directory: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
        REPOSITORY_NAME: luohu1/luohu1.github.io
        BRANCH: master  # The branch the action should deploy to.
        FOLDER: dist  # The folder the action should deploy.
        SINGLE_COMMIT: true
